[package]
name = "ï½Ž-gram"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lindera = { version = "0.12.0", features = ["full"] }
rand = "*"